### PR TITLE
Upgraded to xeus 0.24.2

### PR DESCRIPTION
**Pull request by JohanMabille**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
It weird that build 0 of cppzmq is being pulled

**Comment by JohanMabille** [comment]
We need to rebuild pyzmq because it vendors zeromq on Windows.

**Comment by SylvainCorlay** [comment]
It does not. see my message and my pyzmq feedstock pr.

**Comment by JohanMabille** [comment]
Looks like something went wrong when rebuilding pyzmq-feedstock, it used zeromq 4.3.2 instead of zeromq 4.3.3.

**Pull request merged**
