### PR TITLE
Put xutils and xtraceback in the public API

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by JohanMabille** [comment]
You should add Windows export / import macro to the declaration of classes and functions of the public API.

**Comment by martinRenou** [comment]
Ok, thanks for the review.

We should maybe not put everything in the public API. Only ~4 functions are useful for downstream projects.

**Comment by JohanMabille** [comment]
Fox xutils.hpp, indeed. I let you add what you need for xeus-robot, I will make a pass for the debugger.

**Comment by JohanMabille** [comment]
LGTM

**Pull request merged**
