### PR TITLE
Removed useless flags in static_dependencies build

### PR DESCRIPTION
**Pull request by JohanMabille**
Reverts #218

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Note that #218 could be applied to core xeus, when building the `.so`. I think that it would make sense.

**Comment by JohanMabille** [comment]
We don't want the static biuld of xpython to depend on libxeus.so, otherwise this latter would be installed by the wheel and could be overwrite an installation of xeus-cling for instance (or any other kernel built upon xeus).

**Comment by SylvainCorlay** [comment]
> We don't want the static biuld of xpython to depend on libxeus.so, otherwise this latter would be installed by the wheel and could be overwrite an installation of xeus-cling for instance (or any other kernel built upon xeus).

I agree, but I think it makes sense for people who link with `libxeus.so` in general.

**Comment by JohanMabille** [comment]
WIndows is not affected by this change, no need to wait for appveyor

**Pull request merged**
