### PR TITLE
Use IPython

### LINKED ISSUE #62: Implement showtraceback
A `showtraceback` function should be added in `xeus-python`. It's used by `ipywidgets` https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/widget.py#L191.
An error is thrown when this code is triggered.

### LINKED ISSUE #63: Implement magic commands
Line magics:

- [ ] %alias  
- [ ] %alias_magic  
- [ ] %autoawait  
- [ ] %autocall  
- [ ] %automagic  
- [ ] %autosave  
- [ ] %bookmark  
- [x] %cat  
- [x] %cd  
- [ ] %clear  
- [ ] %colors  
- [ ] %config  
- [ ] %connect_info  
- [ ] %cp  
- [ ] %debug  
- [ ] %dhist  
- [ ] %dirs  
- [ ] %doctest_mode  
- [ ] %ed  
- [ ] %edit  
- [ ] %env  
- [ ] %gui  
- [ ] %hist  
- [x] %history  
- [ ] %killbgscripts  
- [ ] %ldir  
- [ ] %less  
- [ ] %lf  
- [ ] %lk  
- [ ] %ll  
- [ ] %load  
- [x] %load_ext  
- [ ] %loadpy  
- [ ] %logoff  
- [ ] %logon  
- [ ] %logstart  
- [ ] %logstate  
- [ ] %logstop  
- [ ] %ls  
- [ ] %lsmagic  
- [ ] %lx  
- [ ] %macro  
- [ ] %magic  
- [ ] %man  
- [ ] %matplotlib  
- [ ] %mkdir  
- [ ] %more  
- [ ] %mv  
- [ ] %notebook  
- [ ] %page  
- [ ] %pastebin  
- [ ] %pdb  
- [ ] %pdef  
- [ ] %pdoc  
- [ ] %pfile  
- [ ] %pinfo  
- [ ] %pinfo2  
- [ ] %popd  
- [ ] %pprint  
- [ ] %precision  
- [ ] %prun  
- [ ] %psearch  
- [ ] %psource  
- [ ] %pushd  
- [x] %pwd  
- [ ] %pycat  
- [ ] %pylab  
- [ ] %qtconsole  
- [ ] %quickref  
- [x] %recall  
- [ ] %rehashx  
- [ ] %reload_ext  
- [ ] %rep  
- [x] %rerun  
- [ ] %reset  
- [ ] %reset_selective  
- [ ] %rm  
- [ ] %rmdir  
- [ ] %run  
- [ ] %save  
- [ ] %sc  
- [ ] %set_env  
- [ ] %store  
- [ ] %sx  
- [ ] %system  
- [ ] %tb  
- [ ] %time  
- [ ] %timeit  
- [ ] %unalias  
- [ ] %unload_ext  
- [ ] %who  
- [ ] %who_ls  
- [ ] %whos  
- [ ] %xdel  
- [ ] %xmode

Cell magics:

- [ ] %%!  
- [ ] %%HTML  
- [ ] %%SVG  
- [ ] %%bash  
- [ ] %%debug  
- [ ] %%file  
- [ ] %%html  
- [ ] %%javascript  
- [ ] %%js  
- [ ] %%latex  
- [ ] %%capture  
- [ ] %%markdown  
- [ ] %%perl  
- [ ] %%prun  
- [ ] %%pypy  
- [ ] %%python  
- [ ] %%python2  
- [ ] %%python3  
- [ ] %%ruby  
- [ ] %%script  
- [ ] %%sh  
- [ ] %%svg  
- [ ] %%sx  
- [ ] %%system  
- [ ] %%time  
- [x] %%timeit  
- [x] %%writefile

### LINKED ISSUE #224: Matplotlib does not work with xeus-python
On XEUS `0.23.9` I find that using the `@interact` decorator and sliders that they will appear fine and as expected, however when they are attached to figures they don't display properly. 

Here is a minimal example that doesn't work on my system: 

``` python
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
import matplotlib.pyplot as plt
@interact(n=(1,7))
def plotN(n):
    vals = [i for i in range(n)]
    plt.plot(vals)
```

expected behaviour: [img](https://i.imgur.com/dF816YP.png)

actual behaviour: [img](https://i.imgur.com/kkNqJGg.png)

### LINKED ISSUE #359: Output caching: "name '_' is not defined"
I am using xeus-python 0.9.0 and when I try accessing output cache variables (ie _<n> or _) I receive a NameError and the variables are undefined. In IPython these variables are [automatically generated on 1st invocation](https://ipython.readthedocs.io/en/stable/interactive/reference.html#output-caching-system). It's quite a useful feature.

### LINKED ISSUE #399: Implement shell events
IPython implements multiple shell events like post-execute on which users can hook in order to execute code when those events occur. We might want to consider implementing it.

### LINKED ISSUE #402: Automatic import of libraries at startup
Hi,

In IPython, I can automatically import libraries into jupyter notebook by defining start.py under ~/.ipython/profile_default/startup (https://towardsdatascience.com/how-to-automatically-import-your-favorite-libraries-into-ipython-or-a-jupyter-notebook-9c69d89aa343)

I could not locate the config to the same for an xpython kernel.

Please help.

Thanks,
JN

### PR DESCRIPTION
**Pull request by martinRenou**
Fix #62, fix #63, partially fix #224, fix #28, fix #359, fix #399, fix #402

### CODE REVIEW

**Comment by martinRenou** [comment]
It could be interesting to benchmark the starting time with and without this change, see if loading IPython affects start time.

**Comment by martinRenou** [comment]
This is just a simple test for now. Only code execution works with the display hook.

**Comment by martinRenou** [comment]
This could allow getting rid of a lot of code in xeus-python: error traceback, inspection, completion, etc. It would also bring magics support for free, even though some work would still be required to support matplotlib.

**Comment by martinRenou** [comment]
What remains to have a mergeable PR:
- [ ] Keep `user_ns` `global_ns` as a C++ interpreter attribute
- [ ] Find a suitable approach for executing Python code without using `shell.run_cell` (for the debugger and xeus-robot) while getting back the traceback correctly formatted and updating the linecache. We can get rid of xtraceback.cpp if we find a proper solution with IPython.
- [ ] Custom display hook. (Check that SlicerJupyter's display hook can still work with the new approac)
- [ ] Hook clear_output

**Comment by agoose77** [comment]
Wow, this is a really big step for usability. Awesome work!

**Comment by jtpio** [comment]
Epic!

**Pull request merged**
