### PR TITLE
Merge the documentations of jupyterlite-xeus-python and xeus-python

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
Trying to trigger rtd

**Comment by martinRenou** [comment]
Not sure I can build PRs with ReadTheDocs that are not against the default branch. Lets merge and iterate.

**Comment by jtpio** [comment]
> Not sure I can build PRs with ReadTheDocs that are not against the default branch. Lets merge and iterate.

The preview links might be available from the ReadTheDocs admin page?

For example with the `jupyterlite-xeus-python` kernel setup on RTD:

image

**Comment by martinRenou** [comment]
Problem is this is not a PR against the main branch, so ReadTheDocs does not build the PR branch.

Anyway this cannot pass until Thorsten finished https://github.com/jupyter-xeus/xeus-python/pull/600

**Pull request merged**
