### PR TITLE
Fix ipython display monkey patch and improve the display module

### PR DESCRIPTION
**Pull request by martinRenou**
This patches `IPython.core.display` instead of `IPython.display`. So that we should get `Audio`, `IFrame` etc. for free.

It also implements the missing bits of `IPython.core.display` patch.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
How does things behave when IPython is not present? (for what is not missing)

**Comment by martinRenou** [comment]
If IPython is not installed, I suppose

```python
from IPython.core.display import HTML
```

will work, but

```python
from IPython.display import HTML
```

will **not** work.

But I would say that if IPython is not installed, the user should not expect it to work anyway.

Can you actually install Jupyter without ipython?

**Comment by martinRenou** [comment]
@SylvainCorlay That is actually an issue I see with this. ipywidgets and plotly seem to import doing
```python
from IPython.display import display
from IPython.display import display_html
``` 
This means that if we merge this, importing ipywidgets will result in importing IPython as well, which is not the case as of today. What do you think?

**Comment by martinRenou** [comment]
@SylvainCorlay So what do you think? Should we merge this PR?

**Pull request merged**
